---
title: "Central Limit Theorem"
author: "Alex Stephenson"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F, warning=F}
library(dplyr)
library(ggplot2)
library(tidyr)
```


```{r}
sample_from_dist<- function(N, dist){
  # A wrapper function to sample from different distributions 
  # N = sample size
  # dist = probability distribution, can be "normal", "unif", "binom"
  if(dist == "normal"){
    s <- rnorm(N, 100, 10)
  }
  if(dist == "unif"){
    s <- runif(N)
  }
  if(dist == "binom"){
    s <- rbinom(N, 1, prob = 0.5)
  }
  return(s)
}

```

```{r}
simulate <- function(N, dist){
  # Function to simulate different sample mean sizes 
  # N = sample size
  # dist = probability distribution, can be "normal", "unif", "binom"
  sim <- vector(mode = "numeric", length = 100L)
  for(i in 1:100){
    sim[i] <- mean(sample_from_dist(N, dist))
  }
  return(sim)
}
```

Here's an example using the uniform distribution

```{r}
demo <- tibble(
  X_10 = simulate(10, "unif"),
  X_100 = simulate(100, "unif"),
  X_1000 = simulate(1000, "unif")
)

demo %>% 
  pivot_longer(
    cols = everything(), 
    names_to = "samples",
    values_to = "values"
  )%>%
  ggplot(aes(values))+
  geom_density()+
  facet_wrap(~samples)

```